apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: core
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
  selector:
    app: core
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
  namespace: default
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
    spec:
      nodeSelector:
        node_type: core

      containers:
        - name: core
          image: gcr.io/jargon/core:__REPLACE_WITH_TAG__
          imagePullPolicy: IfNotPresent
          env:
            - name: PRISMA_ENDPOINT
              value: 'prisma.default.svc.cluster.local:4466'
            - name: PRISMA_ENV
              value: 'prod'
            - name: PORT
              value: '3000'
